
SCREEN_X = 800
SCREEN_Y = 600

WINDOW_TITLE = "Maze Solver"
WINDOW_COLOR = "white"

CONFIG_TITLE_TEXT = "Maze Configuration"
CONFIG_TITLE_X = 50
CONFIG_TITLE_Y = 10
CONFIG_TITLE_FONT_SIZE = 14

TRANSPARENT_COLOR = WINDOW_COLOR

INPUT_WIDTH = 50

NUM_COLS_INPUT_X = 50
NUM_COLS_INPUT_Y = 45

NUM_ROWS_INPUT_X = 220
NUM_ROWS_INPUT_Y = 45

LOAD_MAZE_BUTTON_X = 360
LOAD_MAZE_BUTTON_Y = 40

SOLVE_ALGO_INPUT_X = 510
SOLVE_ALGO_INPUT_Y = 45
SOLVE_ALGO_INPUT_WIDTH = INPUT_WIDTH * 2
SOLVE_ALGOS = [
    "dfs",
    "bfs",
    "A*"
]

SOLVE_MAZE_BUTTON_X = 635
SOLVE_MAZE_BUTTON_Y = 40
BUTTON_BG_COLOR = "#000000"
BUTTON_FONT_COLOR = "#FFFFFF"

MAZE_X1 = 50
MAZE_Y1 = MAZE_X1 * 2 - 10